// swift-tools-version:5.4
// Generated by cfg-cruby 2.1.0

import PackageDescription

let package = Package(
    name: "CRuby",
    products: [
      .library(name: "CRuby", targets: ["CRuby"]),
    ],
    targets: [
      .systemLibrary(name: "CRuby"),
    ]
)
