/* Generated by cfg-cruby 1.0.0 */
#include "ruby/ruby.h"
#include "ruby/ruby/debug.h"
#include "ruby/ruby/encoding.h"
#include "ruby/ruby/io.h"
#include "ruby/ruby/re.h"
#include "ruby/ruby/thread.h"
#include "ruby/ruby/version.h"
#include "ruby/ruby/vm.h"
